# Use proactive scheduler image and change the entrypoint
FROM tobwiens/proactive-bare-scheduler:master

ENTRYPOINT ["/home/paserver/data/scheduling/bin/proactive-node", "-Dproactive.useIPaddress=true"]
